server:
  port: 8080

spring:
  application:
    name: spring-security

  sql:
    init:
      mode: always

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    show-sql: true

  datasource:
    url: jdbc:mysql://localhost:3306/mydbtweet
    username: admin
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver

jwt:
  public:
    key: "classpath:app.pub"
  private:
    key: "classpath:app.key"